#!/usr/bin/env bash
# This script receives a kill signal from another script running in another terminal
# Kill signal will be caught and ignored then display message instead

msg()
{
	echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2

done
