#!/usr/bin/env bash
# This script gives info about the school file such as
# if the file school exists or if it does not exist and print acordingly
# or if school file is empty or not and make sure its a regular file it will print accordingly

FILE=school
if [ -e $FILE ];then
	echo "$FILE file exists"

	if [ -s $FILE ]; then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi

	if [ -f $FILE ]; then
		echo "$FILE file is a regular file"
	fi

else
	echo "$FILE file does not exist"

fi
